Added Usage Steps
ArasLabs/identity-circular-ref-check pull request #4
Opened 2019-08-02 18:24 UTC by sampoearas

- Added Usage steps to readme
- verified on v12

2019-08-02 21:18 UTC, EliJDonahue requested changes

2019-08-02 21:18 UTC, EliJDonahue commented on README.md
> +1. Aras Innovator installed (version 12.0 preferred)
```suggestion
1. Aras Innovator installed (see "Supported Aras Versions" above)
```

2019-08-05 13:13 UTC, sampoearas commented
Suggestion accepted.

2019-08-06 23:17 UTC, EliJDonahue approved these changes

2019-08-07 12:53 UTC, merged